language: node_js
node_js: node

cache: npm

before_install:
- curl -L https://unpkg.com/@pnpm/self-installer | node

install:
- pnpm i

script:
- pnpm run test:cover

after_success:
- pnpm run coverage
